name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update packages
      run: sudo dpkg --add-architecture i386 && sudo apt-get -y update
    - name: install packages
      run: sudo apt-get -y install build-essential g++-multilib gcc-mingw-w64
    - name: make
      run: make
    - name: make win32
      run: make OSTYPE=win32
