name: C/C++ CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - name: Run add x86 Architecture
      run: sudo dpkg --add-architecture i386 && sudo apt-get -y update
      
    - name: Run install x86 Toolchain
      run: sudo apt-get -y install build-essential g++-multilib
      
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.1
      with:
        action: build
      
    - uses: actions/upload-artifact@v1
      with:
        name: foxbot.so
        path: build/foxbot.so
        
  Windows:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
        
    - name: Remove bad ninja
      shell: cmd
      run: |
          del "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"
          
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.1
      with:
        action: build
        directory: build
        setup-options: -Db_vscrt=mt
      
    - uses: actions/upload-artifact@v1
      with:
        name: foxbot.dll
        path: build/foxbot.dll
